version: "2"

linters:
  enable:
    - errcheck
    - staticcheck
    - unused
    - govet
    - ineffassign

issues:
  exclude-rules:
    # Test files: don't require error checks on helper calls
    - path: _test\.go
      linters:
        - errcheck
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
